Repository 1Coin-FinanceTracker/1CoinClient, pull requests merged in 2023-05, with the labels that each got.

#78 [FT-248] Add paddings between view on DetailAccountScreen
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/detail_account/DetailAccountScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/detail_account/views/DetailAccountExpandedAppBar.kt
Labels: bug

#77 [FT-243] Add investment account type
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/models/Account.kt
  common/src/commonMain/resources/MR/base/strings.xml
  common/src/commonMain/resources/MR/ru/strings.xml
Labels: enhancement

#76 [FT-246] Fix crush 'Zoom range limit must be less than range'
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/peroid_bar_chart/CoinXYChart.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/txs_by_category_chart_block/CategoriesList.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/txs_by_category_chart_block/MainTxsByCategoryChart.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/widgets/AnalyticsTrendWidget.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/PrimitivesExt.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/TransactionsInteractor.kt
Labels: bug

#85 Fix bug with big numbers' text overflow
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/views/StepsEnterTransactionBar.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/views/enter_transaction_controller/AccountSelector.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/views/enter_transaction_controller/CategorySelector.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/peroid_bar_chart/PeriodBarChart.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/txs_by_category_chart_block/CategoriesList.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/txs_by_category_chart_block/HoleTotalLabel.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/txs_by_category_chart_block/MainTxsByCategoryChart.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/HomeTopBar.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/AccountCard.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/transactions/TransactionItem.kt
Labels: bug

#80 [FT-250] Fix bugs with big numbers on AddTransactionScreen
  common/build.gradle.kts
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/common/createFontFamilyResolver.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/AddTransactionScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/views/LabeledAmountField.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/NumberExtensions.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/AddTransactionViewModel.kt
  common/src/desktopMain/kotlin/com/finance_tracker/finance_tracker/core/common/createFontFamilyResolver.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/common/createFontFamilyResolver.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/AmountTextField.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/AutoSizeTextField.kt
  gradle/libs.versions.toml
  ios/Podfile.lock
Labels: bug

#84 [FT-241] Add plans tab and budgets widget (without bussiness-logic)
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/main/MainNavigationGraph.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/tabs/TabsNavigationTree.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/accounts/AccountsActionHandler.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/accounts/AccountsAppBar.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/accounts/AccountsScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/HomeActionHandler.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/HomeScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/views/AccountsWidgetContent.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/views/AddAccountCard.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/views/HomeTopBar.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/views/LastTransactionsEmptyStub.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/views/LastTransactionsWidgetContent.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/PlansActionHandler.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/PlansScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetByCategoriesWidget.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetsByCategoriesHeader.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetsEmptyStub.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/BudgetsView.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/views/PlansTopBar.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/tabs_navigation/TabsNavigationScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/tabs_navigation/tabs/PlansTab.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/widgets/LastTransactionsWidget.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/widgets/MyAccountsWidget.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/di/MainModule.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/navigtion/main/MainNavigationTree.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/models/Budget.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/accounts/AccountsAction.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/accounts/AccountsViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/accounts/analytics/AccountsAnalytics.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/plans/PlansAction.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/plans/PlansViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/plans/analytics/PlansAnalytics.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/plans/di/PlansModule.kt
  common/src/commonMain/resources/MR/base/strings.xml
  common/src/commonMain/resources/MR/files/ic_arrow_down_plans.svg
  common/src/commonMain/resources/MR/files/ic_plans_active.svg
  common/src/commonMain/resources/MR/files/ic_plans_inactive.svg
  common/src/commonMain/resources/MR/ru/strings.xml
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/BudgetCard.kt
  ios/Podfile.lock
Labels: enhancement

#92 [FT-260] Setting up a project for the M1 Pro
  generateIOS.sh
  ios/Podfile.lock
Labels: bug, documentation

#95 [FT-229] My Accounts section on the iOS home screen
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/models/DashboardWidgetData.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/theme/CoinTheme.kt
  ios/AppScreen.swift
  ios/OneCoin.xcodeproj/project.pbxproj
  ios/OneCoin/Assets.xcassets/CardIcons/Contents.json
  ios/OneCoin/Assets.xcassets/CardIcons/DebitCard.imageset/Contents.json
  ios/OneCoin/Assets.xcassets/CardIcons/DebitCard.imageset/DebitCard.svg
  ios/OneCoin/Core/Theme/CoinTheme.swift
  ios/OneCoin/Core/Theme/ThemeManager.swift
  ios/OneCoin/Core/UI/CoinColors+Ext.swift
  ios/OneCoin/Core/UI/CoinColors.swift
  ios/OneCoin/Core/UI/CoinTheme.swift
  ios/OneCoin/Core/UI/Typography.swift
  ios/OneCoin/Core/UI/UIOneCoinConstants.swift
  ios/OneCoin/Core/Views/CoinTabView.swift
  ios/OneCoin/Core/Views/CoinTopAppBar.swift
  ios/OneCoin/Core/Views/CoinWidget.swift
  ios/OneCoin/Core/Views/SVGImageView.swift
  ios/OneCoin/Features/TabScreens/Accounts/Model/AccountCardModel.swift
  ios/OneCoin/Features/TabScreens/Accounts/View/AccountsScreen.swift
  ios/OneCoin/Features/TabScreens/Home/HomeScreen.swift
  ios/OneCoin/Features/TabScreens/Home/HomeTopBar.swift
  ios/OneCoin/Features/TabsNavigation/TabsNavigationScreen.swift
  ios/OneCoin/Features/Widgets/LastTransactionsWidget.swift
  ios/OneCoin/OneCoinApp.swift
Labels: good first issue

#97 [FT-230] Expense trend chart added
  ios/OneCoin.xcodeproj/project.pbxproj
  ios/OneCoin/Core/UI/CoinTheme.swift
  ios/OneCoin/Core/UI/UIOneCoinConstants.swift
  ios/OneCoin/Core/Views/CoinWidget.swift
  ios/OneCoin/Features/TabScreens/Accounts/View/AccountsScreen.swift
  ios/OneCoin/Features/TabScreens/Home/HomeScreen.swift
  ios/OneCoin/Features/Widgets/Accounts/Model/AccountCardModel.swift
  ios/OneCoin/Features/Widgets/Accounts/View/AccountCard.swift
  ios/OneCoin/Features/Widgets/Accounts/View/CardAccountsScreen.swift
  ios/OneCoin/Features/Widgets/LastTransactionsWidget.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/Model/LollipopChartMockData.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/Model/TimelineTypes.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/LollipopChart.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/TotalExpenseChartWidget.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/TotalExpenseChartWidgetContent.swift
Labels: feature

#100 [FT-289] Make the graph in the ExpenseTrend widget interactive
  ios/OneCoin.xcodeproj/project.pbxproj
  ios/OneCoin.xcodeproj/xcshareddata/xcschemes/OneCoin.xcscheme
  ios/OneCoin/Core/Extension/Collection/SafeInCollection.swift
  ios/OneCoin/Core/Extension/Date/Date.swift
  ios/OneCoin/Core/UI/UIOneCoinConstants.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/Model/LollipopChartMockData.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/InteractionWithLollipopChart.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/LollipopChart.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/TotalExpenseChartWidgetContent.swift
Labels: feature

#96 [FT-260] handled BUILD FAILED in generateDummyFramework
  generateIOS.sh
Labels: bug, duplicate

#101 [FT-291] Coordinate DesignSystem with ExpenseTrend
  ios/OneCoin.xcodeproj/project.pbxproj
  ios/OneCoin/Core/UI/UIOneCoinConstants.swift
  ios/OneCoin/Core/Utils/Components/Tabs.swift
  ios/OneCoin/Core/Utils/Preferences/CustomEnvironmentValues.swift
  ios/OneCoin/Core/Utils/Shapes/YAxisDashedLine.swift
  ios/OneCoin/Core/Views/CoinTabView.swift
  ios/OneCoin/Core/Views/CoinWidget.swift
  ios/OneCoin/Features/TabsNavigation/Tab.swift
  ios/OneCoin/Features/TabsNavigation/TabsNavigationScreen.swift
  ios/OneCoin/Features/Widgets/Accounts/View/AccountCard.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/Model/LollipopChartMockData.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/Model/TimelineTypes.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/InteractionWithLollipopChart.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/LollipopChart.swift
  ios/OneCoin/Features/Widgets/TotalExpenseChart/View/TotalExpenseChartWidgetContent.swift
Labels: feature

#93 Add Snackbars
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/core/navigation/NavControllerExt.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/AnalyticsScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/detail_account/DetailAccountActionHandler.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/detail_account/DetailAccountScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/home/HomeScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/plans/PlansScreen.kt
  common/src/androidMain/kotlin/com/finance_tracker/finance_tracker/features/transactions/TransactionsScreen.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/snackbar/SnackbarManager.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/snackbar/SnackbarStateWithScreenParams.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/view_models/BaseViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/view_models/ViewModelExt.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/common/view_models/WrappedFlow.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/di/CoreModule.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/snackbar/SnackbarActionState.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/core/ui/snackbar/SnackbarState.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/data/repositories/TransactionsRepository.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/di/DomainModule.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/TransactionsInteractor.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/transactions/GetTransactionsForChartUseCase.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/transactions/TransactionsInteractor.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/domain/interactors/transactions/UpdateAccountBalanceForTransactionUseCase.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/AddTransactionViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/add_transaction/analytics/AddTransactionAnalytics.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/analytics/delegates/MonthTxsByCategoryDelegate.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/detail_account/DetailAccountAction.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/detail_account/DetailAccountViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/home/HomeViewModel.kt
  common/src/commonMain/kotlin/com/finance_tracker/finance_tracker/features/transactions/TransactionsViewModel.kt
  common/src/commonMain/resources/MR/base/strings.xml
  common/src/commonMain/resources/MR/files/ic_check_circle.svg
  common/src/commonMain/resources/MR/files/ic_cross_circle.svg
  common/src/commonMain/resources/MR/files/ic_undo.svg
  common/src/commonMain/resources/MR/ru/strings.xml
  common/src/commonMain/sqldelight/com/finance_tracker/finance_tracker/data/TransactionsEntity.sq
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/common/view_models/BaseViewModelExtensions.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/theme/CoinTheme.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/ComposeScreen.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/snackbar/CoinSnackbar.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/snackbar/CoinSnackbarHost.kt
  common/src/jvmMain/kotlin/com/finance_tracker/finance_tracker/core/ui/snackbar/CoinSnackbarHostState.kt
Labels: enhancement
